export enum ErrorCodes {
  RANDOM_WORD_ERROR = 1,
  SESSION_ERROR = 2,
  GENERAL_ERROR = 3,
  PARAMS_ERROR = 4,
  LOCAL_DICTIONARY_ERROR = 5,
  INVALID_WORD = 6,
  CONFIGURATION = 7,
  SESSION_NO_GAME_ERROR = 8,
  SESSION_GAME_FINISHED_ERROR = 9,
}
