import { IDictionary } from '@repo/common-types';

export const flagList: IDictionary<string> = {
  af: 'za',
  sq: 'al',
  be: 'by',
  bs: 'ba',
  bg: 'bg',
  hr: 'hr',
  cs: 'cz',
  da: 'dk',
  nl: 'nl',
  en: 'us',
  eo: 'esperanto',
  et: 'ee',
  fi: 'fi',
  fr: 'fr',
  de: 'de',
  hu: 'hu',
  is: 'is',
  ga: 'ie',
  it: 'it',
  la: 'spqr',
  lv: 'lv',
  lt: 'lt',
  mk: 'mk',
  no: 'no',
  pl: 'pl',
  pt: 'pt',
  ro: 'ro',
  ru: 'ru',
  sr: 'rs',
  sk: 'sk',
  sl: 'si',
  es: 'es',
  sv: 'se',
  tr: 'tr',
};
export const countryNamesList: IDictionary<string> = {
  af: 'South Africa',
  sq: 'Albania',
  be: 'Belarus',
  bs: 'Bosnia and Herzegovina',
  bg: 'Bulgaria',
  hr: 'Croatia',
  cs: 'Czechia',
  da: 'Denmark',
  nl: 'Netherlands, Kingdom of the',
  en: 'United States of America',
  eo: 'esperanto',
  et: 'Estonia',
  fi: 'Finland',
  fr: 'France',
  de: 'Germany',
  hu: 'Hungary',
  is: 'Iceland',
  ga: 'Ireland',
  it: 'Italy',
  la: 'Roman Empire, SPQR',
  lv: 'Latvia',
  lt: 'Lithuania',
  mk: 'North Macedonia',
  no: 'Norway',
  pl: 'Poland',
  pt: 'Portugal',
  ro: 'Romania',
  ru: 'Russian Federation',
  sr: 'Serbia',
  sk: 'Slovakia',
  sl: 'Slovenia',
  es: 'Spain',
  sv: 'Sweden',
  tr: 'Türkiye',
};
export const languageList: IDictionary<string> = {
  af: 'afrikaans',
  sq: 'albanian',
  be: 'belarusian',
  bs: 'bosnian',
  bg: 'bulgarian',
  hr: 'croatian',
  cs: 'czech',
  da: 'danish',
  nl: 'dutch',
  en: 'english',
  eo: 'esperanto',
  et: 'estonian',
  fi: 'finnish',
  fr: 'french',
  de: 'german',
  hu: 'hungarian',
  is: 'icelandic',
  ga: 'irish',
  it: 'italian',
  la: 'latin',
  lv: 'latvian',
  lt: 'lithuanian',
  mk: 'macedonian',
  no: 'norwegian',
  pl: 'polish',
  pt: 'portuguese',
  ro: 'romanian',
  ru: 'russian',
  sr: 'serbian',
  sk: 'slovak',
  sl: 'slovenian',
  es: 'spanish',
  sv: 'swedish',
  tr: 'turkish',
};
